server:
  port: 8080
spring:
  security:
    cors:
      enabled:
        paths: ${SPRING_SECURITY_CORS_ENABLED}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-app.xml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:photo;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 4MB

